/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carloslanza_lab6p2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class CarlosLanza_Lab6P2 extends javax.swing.JFrame {

    /**
     * Creates new form CarlosLanza_Lab6P21
     */
    public CarlosLanza_Lab6P2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_crearEquipos = new javax.swing.JDialog();
        bg_crearEquipos = new javax.swing.JPanel();
        txt_crearEquipos = new javax.swing.JLabel();
        txt_nombreEquipo = new javax.swing.JLabel();
        txt_paisEquipo = new javax.swing.JLabel();
        txt_ciudad = new javax.swing.JLabel();
        txt_estadio = new javax.swing.JLabel();
        tf_paisEquipo = new javax.swing.JTextField();
        tf_nombreEquipo = new javax.swing.JTextField();
        tf_ciudad = new javax.swing.JTextField();
        tf_estadio = new javax.swing.JTextField();
        btn_agregarEquipo = new javax.swing.JButton();
        frame_transferencias = new javax.swing.JDialog();
        bg_transferencias = new javax.swing.JPanel();
        txt_transferencias = new javax.swing.JLabel();
        txt_jugadores = new javax.swing.JLabel();
        txt_equipos = new javax.swing.JLabel();
        btn_transferir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipos_tree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jugadores_list = new javax.swing.JList<>();
        frame_crearJugadores = new javax.swing.JDialog();
        bg_crearJugadores = new javax.swing.JPanel();
        txt_crearJugadores = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txt_edad = new javax.swing.JLabel();
        txt_posicion = new javax.swing.JLabel();
        tf_nombreJugador = new javax.swing.JTextField();
        spinner_edad = new javax.swing.JSpinner();
        cb_posicion = new javax.swing.JComboBox<>();
        btn_agrearJugador = new javax.swing.JButton();
        jugadores_pp = new javax.swing.JPopupMenu();
        modificarJugador_pp = new javax.swing.JMenuItem();
        eliminarJugador_pp = new javax.swing.JMenuItem();
        bg_home = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_crearEquipos = new javax.swing.JButton();
        btn_crearJugadores = new javax.swing.JButton();
        btn_transferencias = new javax.swing.JButton();
        txt_bienvenido = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_opciones = new javax.swing.JMenu();
        opcion_crearEquipo = new javax.swing.JMenuItem();
        opcion_crearJugadores = new javax.swing.JMenuItem();
        opcion_transferencias = new javax.swing.JMenuItem();
        menu_ayuda = new javax.swing.JMenu();

        frame_crearEquipos.setAutoRequestFocus(false);
        frame_crearEquipos.setBackground(new java.awt.Color(204, 255, 204));
        frame_crearEquipos.setMaximumSize(new java.awt.Dimension(615, 470));
        frame_crearEquipos.setMinimumSize(new java.awt.Dimension(615, 470));
        frame_crearEquipos.setPreferredSize(new java.awt.Dimension(615, 470));

        bg_crearEquipos.setBackground(new java.awt.Color(204, 255, 204));

        txt_crearEquipos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_crearEquipos.setText("Crear Equipos");

        txt_nombreEquipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nombreEquipo.setForeground(new java.awt.Color(51, 51, 255));
        txt_nombreEquipo.setText("Nombre del Equipo");

        txt_paisEquipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_paisEquipo.setForeground(new java.awt.Color(51, 51, 255));
        txt_paisEquipo.setText("Pais del Equipo");

        txt_ciudad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_ciudad.setForeground(new java.awt.Color(51, 51, 255));
        txt_ciudad.setText("Estadio");

        txt_estadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_estadio.setForeground(new java.awt.Color(51, 51, 255));
        txt_estadio.setText("Ciudad");

        tf_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ciudadActionPerformed(evt);
            }
        });

        tf_estadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_estadioActionPerformed(evt);
            }
        });

        btn_agregarEquipo.setText("Agregar");

        javax.swing.GroupLayout bg_crearEquiposLayout = new javax.swing.GroupLayout(bg_crearEquipos);
        bg_crearEquipos.setLayout(bg_crearEquiposLayout);
        bg_crearEquiposLayout.setHorizontalGroup(
            bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(txt_crearEquipos))
                    .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                                .addComponent(txt_paisEquipo)
                                .addGap(108, 108, 108)
                                .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                                .addComponent(txt_nombreEquipo)
                                .addGap(79, 79, 79)
                                .addComponent(tf_nombreEquipo))
                            .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ciudad)
                                    .addComponent(txt_estadio))
                                .addGap(162, 162, 162)
                                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_ciudad)
                                    .addComponent(tf_estadio)))))
                    .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btn_agregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        bg_crearEquiposLayout.setVerticalGroup(
            bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_crearEquiposLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txt_crearEquipos)
                .addGap(30, 30, 30)
                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paisEquipo)
                    .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreEquipo)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_estadio)
                    .addComponent(tf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ciudad)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btn_agregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_crearEquiposLayout = new javax.swing.GroupLayout(frame_crearEquipos.getContentPane());
        frame_crearEquipos.getContentPane().setLayout(frame_crearEquiposLayout);
        frame_crearEquiposLayout.setHorizontalGroup(
            frame_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_crearEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_crearEquiposLayout.setVerticalGroup(
            frame_crearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_crearEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frame_transferencias.setMaximumSize(new java.awt.Dimension(615, 470));
        frame_transferencias.setMinimumSize(new java.awt.Dimension(615, 470));
        frame_transferencias.setPreferredSize(new java.awt.Dimension(615, 470));

        bg_transferencias.setBackground(new java.awt.Color(255, 255, 204));

        txt_transferencias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_transferencias.setText("Transferencias");

        txt_jugadores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_jugadores.setText("Jugadores");

        txt_equipos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_equipos.setText("Equipos");

        btn_transferir.setText("Transferir ->");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        equipos_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(equipos_tree);

        jugadores_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugadores_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jugadores_list);

        javax.swing.GroupLayout bg_transferenciasLayout = new javax.swing.GroupLayout(bg_transferencias);
        bg_transferencias.setLayout(bg_transferenciasLayout);
        bg_transferenciasLayout.setHorizontalGroup(
            bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_transferenciasLayout.createSequentialGroup()
                .addGroup(bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_transferenciasLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(txt_transferencias))
                    .addGroup(bg_transferenciasLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_jugadores)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(btn_transferir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_equipos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        bg_transferenciasLayout.setVerticalGroup(
            bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_transferenciasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txt_transferencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jugadores)
                    .addComponent(txt_equipos))
                .addGroup(bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_transferenciasLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_transferir))
                    .addGroup(bg_transferenciasLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(bg_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_transferenciasLayout = new javax.swing.GroupLayout(frame_transferencias.getContentPane());
        frame_transferencias.getContentPane().setLayout(frame_transferenciasLayout);
        frame_transferenciasLayout.setHorizontalGroup(
            frame_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_transferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_transferenciasLayout.setVerticalGroup(
            frame_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_transferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frame_crearJugadores.setMaximumSize(new java.awt.Dimension(615, 470));
        frame_crearJugadores.setMinimumSize(new java.awt.Dimension(615, 470));
        frame_crearJugadores.setPreferredSize(new java.awt.Dimension(615, 470));

        bg_crearJugadores.setBackground(new java.awt.Color(204, 204, 255));
        bg_crearJugadores.setForeground(new java.awt.Color(255, 255, 255));

        txt_crearJugadores.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txt_crearJugadores.setText("Crear Jugadores");

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nombre.setText("Nombre");

        txt_edad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_edad.setText("Edad");

        txt_posicion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_posicion.setText("Posicion");

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        btn_agrearJugador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agrearJugador.setText("Agregar");
        btn_agrearJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agrearJugadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg_crearJugadoresLayout = new javax.swing.GroupLayout(bg_crearJugadores);
        bg_crearJugadores.setLayout(bg_crearJugadoresLayout);
        bg_crearJugadoresLayout.setHorizontalGroup(
            bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_crearJugadoresLayout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(txt_crearJugadores)
                .addGap(135, 135, 135))
            .addGroup(bg_crearJugadoresLayout.createSequentialGroup()
                .addGroup(bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg_crearJugadoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_agrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg_crearJugadoresLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre)
                            .addComponent(txt_edad)
                            .addComponent(txt_posicion))
                        .addGap(79, 79, 79)
                        .addGroup(bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreJugador)
                            .addComponent(spinner_edad)
                            .addComponent(cb_posicion, 0, 135, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg_crearJugadoresLayout.setVerticalGroup(
            bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_crearJugadoresLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txt_crearJugadores)
                .addGap(50, 50, 50)
                .addGroup(bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre)
                    .addComponent(tf_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_edad)
                    .addComponent(spinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(bg_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_posicion)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btn_agrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_crearJugadoresLayout = new javax.swing.GroupLayout(frame_crearJugadores.getContentPane());
        frame_crearJugadores.getContentPane().setLayout(frame_crearJugadoresLayout);
        frame_crearJugadoresLayout.setHorizontalGroup(
            frame_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_crearJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_crearJugadoresLayout.setVerticalGroup(
            frame_crearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_crearJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        modificarJugador_pp.setText("Modificar");
        modificarJugador_pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarJugador_ppActionPerformed(evt);
            }
        });
        jugadores_pp.add(modificarJugador_pp);

        eliminarJugador_pp.setText("Eliminar");
        eliminarJugador_pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarJugador_ppActionPerformed(evt);
            }
        });
        jugadores_pp.add(eliminarJugador_pp);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(615, 470));
        setMinimumSize(new java.awt.Dimension(615, 470));
        setPreferredSize(new java.awt.Dimension(615, 470));

        bg_home.setBackground(new java.awt.Color(0, 255, 204));
        bg_home.setMaximumSize(new java.awt.Dimension(615, 470));
        bg_home.setMinimumSize(new java.awt.Dimension(615, 470));
        bg_home.setPreferredSize(new java.awt.Dimension(615, 470));

        jToolBar1.setBackground(new java.awt.Color(102, 255, 204));
        jToolBar1.setRollover(true);

        btn_crearEquipos.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_crearEquipos.setText("Crear equipos");
        btn_crearEquipos.setFocusable(false);
        btn_crearEquipos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_crearEquipos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_crearEquipos);

        btn_crearJugadores.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_crearJugadores.setText("Crear jugadores");
        btn_crearJugadores.setFocusable(false);
        btn_crearJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_crearJugadores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_crearJugadores);

        btn_transferencias.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_transferencias.setText("Transferencias");
        btn_transferencias.setFocusable(false);
        btn_transferencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_transferencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transferenciasActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_transferencias);

        txt_bienvenido.setBackground(new java.awt.Color(0, 153, 255));
        txt_bienvenido.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        txt_bienvenido.setText("Bienvenido a Boroa League Fantasy");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.png"))); // NOI18N

        javax.swing.GroupLayout bg_homeLayout = new javax.swing.GroupLayout(bg_home);
        bg_home.setLayout(bg_homeLayout);
        bg_homeLayout.setHorizontalGroup(
            bg_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_homeLayout.createSequentialGroup()
                .addGroup(bg_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_homeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_homeLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(bg_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bienvenido)
                            .addGroup(bg_homeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(img)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        bg_homeLayout.setVerticalGroup(
            bg_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_bienvenido)
                .addGap(12, 12, 12)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jMenuBar1.setToolTipText("Crear equipos\ncrear jugadores\nTransferencias\n");

        menu_opciones.setText("Opciones ");
        menu_opciones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menu_opcionesStateChanged(evt);
            }
        });
        menu_opciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu_opcionesMenuSelected(evt);
            }
        });
        menu_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_opcionesActionPerformed(evt);
            }
        });

        opcion_crearEquipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcion_crearEquipo.setText("Crear Equipo");
        opcion_crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_crearEquipoActionPerformed(evt);
            }
        });
        menu_opciones.add(opcion_crearEquipo);

        opcion_crearJugadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcion_crearJugadores.setText("Crear Jugadores");
        opcion_crearJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_crearJugadoresActionPerformed(evt);
            }
        });
        menu_opciones.add(opcion_crearJugadores);

        opcion_transferencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcion_transferencias.setText("Transferencias");
        opcion_transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_transferenciasActionPerformed(evt);
            }
        });
        menu_opciones.add(opcion_transferencias);

        jMenuBar1.add(menu_opciones);

        menu_ayuda.setText("Ayuda ");
        jMenuBar1.add(menu_ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ciudadActionPerformed

    private void tf_estadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_estadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_estadioActionPerformed

    private void menu_opcionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menu_opcionesStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_opcionesStateChanged

    private void menu_opcionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_opcionesMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_opcionesMenuSelected

    private void menu_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_opcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_opcionesActionPerformed

    private void btn_transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transferenciasActionPerformed
        
    }//GEN-LAST:event_btn_transferenciasActionPerformed

    private void opcion_crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_crearEquipoActionPerformed
        frame_crearEquipos.setVisible(true);
    }//GEN-LAST:event_opcion_crearEquipoActionPerformed

    private void opcion_transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_transferenciasActionPerformed
        frame_transferencias.setVisible(true);
    }//GEN-LAST:event_opcion_transferenciasActionPerformed

    private void opcion_crearJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_crearJugadoresActionPerformed
        frame_crearJugadores.setVisible(true);
    }//GEN-LAST:event_opcion_crearJugadoresActionPerformed

    private void btn_agrearJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agrearJugadorMouseClicked
        if (btn_agrearJugador.getText().equals("Agregar")) {
            String nombre = tf_nombreJugador.getText();
            int edad = (int)spinner_edad.getValue();
            String posición = cb_posicion.getSelectedItem().toString();
            
            jugadores.add(new Jugador(nombre,edad,posición));
            llenarListaJugadores();
            
            tf_nombreJugador.setText("");
            spinner_edad.setValue(0);
            cb_posicion.setSelectedItem("Portero");

            JOptionPane.showMessageDialog(frame_crearJugadores, "Jugador creado exitosamente!");
        } else {
            String nombre = tf_nombreJugador.getText();
            for (int i = 0; i < jugadores.size(); i++) {
                if (jugadores.get(i).getNombre().equals(nombre)) {
                    Jugador jugador = jugadores.get(i);
                    jugador.setNombre(tf_nombreJugador.getText());
                    jugador.setEdad((int)spinner_edad.getValue());
                    jugador.setPosicion(cb_posicion.getSelectedItem().toString());
                    break;
                }
            }
            frame_crearJugadores.setVisible(false);
            btn_agrearJugador.setText("Agregar");
        }
    }//GEN-LAST:event_btn_agrearJugadorMouseClicked

    private void jugadores_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugadores_listMouseClicked
        if (evt.isMetaDown()) {           
            jugadores_pp.show(jugadores_list, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jugadores_listMouseClicked

    private void modificarJugador_ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarJugador_ppActionPerformed
        String nombre = jugadores_list.getSelectedValue();
        
        if (!jugadores.isEmpty()) {
            for (int i = 0; i < jugadores.size(); i++) {
                if (jugadores.get(i).getNombre().equals(nombre)) {
                    tf_nombreJugador.setText(nombre);
                    spinner_edad.setValue(jugadores.get(i).getEdad());
                    cb_posicion.setSelectedItem(jugadores.get(i).getPosicion());
                    break;
                }
            }

            frame_transferencias.setVisible(false);
            frame_crearJugadores.setVisible(true);

            btn_agrearJugador.setText("Modificar");
        } else {
            JOptionPane.showMessageDialog(frame_transferencias, "No hay nada que modificar!");
        }
    }//GEN-LAST:event_modificarJugador_ppActionPerformed

    private void eliminarJugador_ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarJugador_ppActionPerformed
        String nombre = jugadores_list.getSelectedValue();
        
        if (!jugadores.isEmpty()) {
            int posicion = 0;
            for (int i = 0; i < jugadores.size(); i++) {
                if (jugadores.get(i).getNombre().equals(nombre)) {
                    posicion = i;
                    break;
                }
            }
            jugadores.remove(posicion);
            llenarListaJugadores();
        } else {
            JOptionPane.showMessageDialog(frame_transferencias, "No hay nada que eliminar!");
        }
    }//GEN-LAST:event_eliminarJugador_ppActionPerformed

    public void llenarListaJugadores() {
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();
        for (int i = 0; i < jugadores.size(); i++) {
            modelo.addElement(jugadores.get(i).getNombre());
        }

        jugadores_list.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarlosLanza_Lab6P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarlosLanza_Lab6P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarlosLanza_Lab6P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarlosLanza_Lab6P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarlosLanza_Lab6P2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_crearEquipos;
    private javax.swing.JPanel bg_crearJugadores;
    private javax.swing.JPanel bg_home;
    private javax.swing.JPanel bg_transferencias;
    private javax.swing.JButton btn_agrearJugador;
    private javax.swing.JButton btn_agregarEquipo;
    private javax.swing.JButton btn_crearEquipos;
    private javax.swing.JButton btn_crearJugadores;
    private javax.swing.JButton btn_transferencias;
    private javax.swing.JButton btn_transferir;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JMenuItem eliminarJugador_pp;
    private javax.swing.JTree equipos_tree;
    private javax.swing.JDialog frame_crearEquipos;
    private javax.swing.JDialog frame_crearJugadores;
    private javax.swing.JDialog frame_transferencias;
    private javax.swing.JLabel img;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> jugadores_list;
    private javax.swing.JPopupMenu jugadores_pp;
    private javax.swing.JMenu menu_ayuda;
    private javax.swing.JMenu menu_opciones;
    private javax.swing.JMenuItem modificarJugador_pp;
    private javax.swing.JMenuItem opcion_crearEquipo;
    private javax.swing.JMenuItem opcion_crearJugadores;
    private javax.swing.JMenuItem opcion_transferencias;
    private javax.swing.JSpinner spinner_edad;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JTextField tf_nombreJugador;
    private javax.swing.JTextField tf_paisEquipo;
    private javax.swing.JLabel txt_bienvenido;
    private javax.swing.JLabel txt_ciudad;
    private javax.swing.JLabel txt_crearEquipos;
    private javax.swing.JLabel txt_crearJugadores;
    private javax.swing.JLabel txt_edad;
    private javax.swing.JLabel txt_equipos;
    private javax.swing.JLabel txt_estadio;
    private javax.swing.JLabel txt_jugadores;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_nombreEquipo;
    private javax.swing.JLabel txt_paisEquipo;
    private javax.swing.JLabel txt_posicion;
    private javax.swing.JLabel txt_transferencias;
    // End of variables declaration//GEN-END:variables

    ArrayList<Jugador> jugadores = new ArrayList<>();
}
